### ISSUE TITLE
HTTP ERROR: 500

### ISSUE THREAD

**Issue by kvazimode** [osobolev/bugs#1]
Problem accessing /bug. Reason:

    freemarker.template.TemplateNotFoundException: Template not found for name "bug.html".
The name was interpreted by this TemplateLoader: ClassTemplateLoader(resourceLoaderClass=common.TemplateUtil, basePackagePath="" /* relatively to resourceLoaderClass pkg */).

Это то, что выдает **любая** страница.
У меня одного так?
Прицепил файл, в котором указан отрывок лога запуска WebServer.java.
[error.txt](https://github.com/osobolev/bugs/files/256046/error.txt)
Что-то не так с TamplateLoader'ом. Погуглил вопрос - говорят, что нужно указывать конкретный путь для заготовки. Но, ведь раньше мы его не указывали и всё работало нормально...
К слову, тот проект, который мы делали раньше, с freemarker'ом, запускается без проблем. И код утилиты практически один-в-один (незначительные изменения).
Сравнение утилит: 
[utils.txt](https://github.com/osobolev/bugs/files/256098/utils.txt)
Пробовал указать jetty версии 9.3.8.v20160314 - помогло.

**Comment by osobolev** [comment]
Я исправил загрузку шаблонов. Эта ошибка происходила из-за того, что мы перенесли класс TemplateUtil в пакет common, а указание new ClassTemplateLoader(TemplateUtil.class, "") ищет шаблон в той же папке, что и класс TemplateUtil, т.е. в папке common. Я заменил на new ClassTemplateLoader(TemplateUtil.class, "/") - теперь поиск будет в корне папки resources. Также добавил кодировку шаблона по умолчанию.

Обновите код из репозитория (сделайте update).

**Comment by kvazimode** [comment]
Теперь всё работает
